### ISSUE TITLE
Memory leak in DiskSpaceMoniotor inside SingleChronicleQueue.java

### ISSUE THREAD

**Issue by anirudh-striim** [OpenHFT/Chronicle-Queue#630] opened 2019-11-15 23:20 UTC
I am using chronicles-bom with version 2.17.48 and I see that the disk-space check happens by default in the chronicles system. I am running into an issue where fileStoreCacheMap object inside DiskSpaceMonitor.java class is not cleared in memory for some reason and its bloating up the memory.

Here is a snap of the heap dump attached.

![image](https://user-images.githubusercontent.com/23368380/68982350-79163a00-07bb-11ea-9209-09119e2389c8.png)

**Comment by dpisklov** [comment] 2019-11-18 22:13
How many files you have? What's the roll cycle you use? This can only happen if you store A LOT of files potentially on various file stores (a.k.a mount points), if all your queue files are on the same mount point the number of entries in a map is number of queue files your system went through and that can't be a lot unless you are using something like secondly roll cycle and your system runs for quite a long time.

**Comment by dpisklov** [comment] 2019-11-18 22:33
I just realized this is mostly a duplicate of #612? 
I just added a possibility to disable disk space monitor, you can specify -Dchronicle.disk.monitor.disable=true and the problem should go away. That said, I have a feeling that you're doing something strange as none of our clients (even those having loads of queues) have ever seen this problem.

**Comment by anirudh-striim** [comment] 2019-11-18 23:14
The stack is the same as that of #612. The flag to disable helps for now. Please let me know which version has that fix and I will use that. 

The scenario that we have is pretty straight forward. We have multiple queues created and written into, the rate of which is dependent on the load that we get. It keeps changing. And yes, at a given point of times, we might have A LOT of files opened, but all on the same mount point currently. There is no roll cycle that we explicitly set.

**Comment by dpisklov** [comment] 2019-11-19 14:00
@anirudh-striim if this happens again can you expand the dump and see what object is (are) actually taking up memory? I made a small change to use String instead of File object as a key for the map, and that's available together with change that adds the flag starting from BOM 2.17.458 - try that and let us know.

**Comment by dpisklov** [comment] 2020-03-30 12:58
@anirudh-striim have you been able to retest/reproduce this or can we close this issue?

**Comment by dpisklov** [comment] 2020-04-22 11:13
Closing due to no response - please reopen if it still happens

**Closed by dpisklov** 2020-04-22 11:13 UTC

**Comment by hft-team-city** [comment] 2020-04-22 14:26
Released in [Chronicle-Queue-5.19.11](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.19.11), [BOM-2.19.116](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.116)
