### ISSUE TITLE
If queue values are in more more than one file I have to move to the next index manually.

### ISSUE THREAD

**Issue by imalygin** [OpenHFT/Chronicle-Queue#259] opened 2016-05-27 00:53 UTC
Here is the code demonstrating the issue I've struggled with

```
package org.imalygin;

import net.openhft.chronicle.queue.ChronicleQueueBuilder;
import net.openhft.chronicle.queue.ExcerptAppender;
import net.openhft.chronicle.queue.ExcerptTailer;
import net.openhft.chronicle.queue.RollCycles;
import net.openhft.chronicle.queue.impl.RollingChronicleQueue;
import net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder;
import net.openhft.chronicle.wire.DocumentContext;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;

public class Demo {

    public static void main(String[] args) throws Exception {
        // creates a queue with TEST_SECONDLY rolling cycle. 
        Demo demo = new Demo();

        // writes two strings immediately and one string with 2 seconds delay
        demo.writeStrings();

        System.out.println(demo.readNextString());
        System.out.println(demo.readNextString());
        // here is how I expected it to work, but it fails with NPE
        // System.out.println(demo.readNextString());

        // here is what I have to do to make it work
        System.out.println(demo.readStringWithManualIndexAdvance());
    }

    private String readNextString() {
        DocumentContext readingContext = tailer.readingDocument();
        String res = readingContext.wire().read().text();
        readingContext.close();
        return res;
    }

    private String readStringWithManualIndexAdvance() {
        tailer.moveToIndex(rollCycle.toIndex(rollCycle.toCycle(tailer.index()) + 2, 0));
        return readNextString();
    }

   private void writeStrings() throws Exception {
        DocumentContext writingContext = appender.writingDocument();
        writingContext.wire()
                .write().bytes(stringsToPut.get(0).getBytes());
        writingContext.close();

        writingContext = appender.writingDocument();
        writingContext.wire().write().bytes(stringsToPut.get(1).getBytes());
        writingContext.close();

        Thread.sleep(2000);

        writingContext = appender.writingDocument();
        writingContext.wire().write().bytes(stringsToPut.get(2).getBytes());
        writingContext.close();
    }

    private final ExcerptAppender appender;
    private final ExcerptTailer tailer;
    private final List<String> stringsToPut;
    private final RollCycles rollCycle;

    private Demo() throws IOException {
        Path dir = Files.createTempDirectory("demo");
        rollCycle = RollCycles.TEST_SECONDLY;
        SingleChronicleQueueBuilder builder = ChronicleQueueBuilder
                .single(dir.toString())
                .rollCycle(rollCycle);
        RollingChronicleQueue queue = builder.build();

        appender = queue.createAppender();
        tailer = queue.createTailer();

        stringsToPut = Arrays.asList("one", "two", "three");
    }

 }
```

As far as I understand idea of a tailer, it's an abstraction from the way how the data is actually stored. But in this example it appears that the way data is stored affects the way how I have to read it. Unfortunately, tailer doesn't work with rolled files transparently. 

Is it the way it's supposed to work or I'm missing something important?

**Comment by peter-lawrey** [comment] 2016-05-27 07:19
I think the problem is that there was no messages for a whole cycle. In
daily terms this would mean no messages for a whole day. Never the less it
should still roll.
On 27 May 2016 1:53 am, "imalygin" <notifications@github.com> wrote:

Here is the code demonstrating the issue I've struggled with

package org.imalygin;

import net.openhft.chronicle.queue.ChronicleQueueBuilder;
import net.openhft.chronicle.queue.ExcerptAppender;
import net.openhft.chronicle.queue.ExcerptTailer;
import net.openhft.chronicle.queue.RollCycles;
import net.openhft.chronicle.queue.impl.RollingChronicleQueue;
import net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder;
import net.openhft.chronicle.wire.DocumentContext;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;

public class Demo {

    private final ExcerptAppender appender;
    private final ExcerptTailer tailer;
    private final List<String> stringsToPut;
    private final RollCycles rollCycle;

    private Demo() throws IOException {
        Path dir = Files.createTempDirectory("demo");
        rollCycle = RollCycles.TEST_SECONDLY;
        SingleChronicleQueueBuilder builder = ChronicleQueueBuilder
                .single(dir.toString())
                .rollCycle(rollCycle);
        RollingChronicleQueue queue = builder.build();

        appender = queue.createAppender();
        tailer = queue.createTailer();

        stringsToPut = Arrays.asList("one", "two", "three");
    }

    private void writeStrings() throws Exception {
        DocumentContext writingContext = appender.writingDocument();
        writingContext.wire()
                .write().bytes(stringsToPut.get(0).getBytes());
        writingContext.close();

        writingContext = appender.writingDocument();
        writingContext.wire().write().bytes(stringsToPut.get(1).getBytes());
        writingContext.close();

        Thread.sleep(2000);

        writingContext = appender.writingDocument();
        writingContext.wire().write().bytes(stringsToPut.get(2).getBytes());
        writingContext.close();
    }

    private String readNextString() {
        DocumentContext readingContext = tailer.readingDocument();
        String res = readingContext.wire().read().text();
        readingContext.close();
        return res;
    }

    private String readStringWithManualIndexAdvance() {
        tailer.moveToIndex(rollCycle.toIndex(rollCycle.toCycle(tailer.index())
+ 2, 0));
        return readNextString();
    }

    public static void main(String[] args) throws Exception {

        Demo demo = new Demo();

        // writes two strings immediately and one string with 2 seconds delay
        demo.writeStrings();

        System.out.println(demo.readNextString());
        System.out.println(demo.readNextString());
        // here is how I expected it to work, but it fails with NPE
        // System.out.println(demo.readNextString());

        // here is what I have to do to make it work
        System.out.println(demo.readStringWithManualIndexAdvance());
    }

}

As far as I understand idea of a tailer, it's an abstraction from the way
how the data is actually stored. But in this example it appears that the
way data is represented affects the way how I have to read it.
Unfortunately, tailer doesn't work with rolled files transparently.

Is it the way it's supposed to work or I'm missing something important?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenHFT/Chronicle-Queue/issues/259>, or mute the thread
<https://github.com/notifications/unsubscribe/ABBU8UYTeYutpAc_ZgNQdzdRVw-TZFkHks5qFkB0gaJpZM4IoFRo>
.

**Comment by peter-lawrey** [comment] 2016-06-28 07:34
bump, this is still an issue if you miss an entire cycle.

**Comment by RobAustin** [comment] 2016-07-19 12:50
I'll retest this, its possible this is now fixed...

**Comment by RobAustin** [comment] 2016-07-19 12:54
I reran the test above, ( which is not exactly a unit test, so hard to tell if its working as you would expect ), but from he output (  and using ' System.out.println(demo.readNextString());' for the third item ) - I think this is now fixed. Please raise another issue if this is not the case. Regards Rob

**Closed by RobAustin** 2016-07-19 12:54 UTC
