### ISSUE TITLE
How to delete a file located inside Chronicle Queue?

### ISSUE THREAD

**Issue by osnatn1984** [OpenHFT/Chronicle-Queue#359] opened 2017-07-03 04:42 UTC
Hi,

I am using ChronicleQueue object to perform some files processing. I notice that when I am trying to delete a file in linux while it is still in the chronicle – the file is not completely deleted (it still holds space in the memory and you can see it using the " lsof +L1" command).
The file can be completely deleted if the queue is closed, but this means it can't process other files in the queue as well…
Do you have any idea how we can delete one file from the queue without closing the queue completely?

Thanks,
Osnat.

**Comment by epickrram** [comment] 2017-07-03 09:02
Hi Osnat,
can you provide some more information:

   * OS
   * Chronicle-Queue version
   * JDK version

Example code that demonstrates the issue would be helpful.

**Comment by osnatn1984** [comment] 2017-07-04 03:10
OS: CentOs 7
Chronicle queue jar :  chronicle-queue-4.5.21.jar
JDK: 1.8.0_111

Example code that creates the queue:

              ChronicleQueue queue = ChronicleQueueBuilder
                           .single(config.queueDirectory())
                           .rollCycle(RollCycles.HOURLY)
                           .build();

Thanks,
Osnat

**Comment by dpisklov** [comment] 2017-11-23 11:11
@osnatn1984 
I ran simple unit test. Chronicle Queue holds reference to a file until it rolls to new Roll cycle. Deleting current roll cycle's file doesn't unmap the file from memory, and that is intended behaviour. If you need to delete files generated by Chronicle you need to delete them after they roll. If you need to do that often, consider changing the roll cycle to RollCycles.MINUTELY - then you will have new file every minute.
I'm closing issue for now, feel free to revert if you need more help.

**Closed by dpisklov** 2017-11-23 11:11 UTC
