### ISSUE TITLE
Recovery timeout + rolling

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#392] opened 2017-10-30 19:50 UTC
I've written a test net.openhft.chronicle.queue.impl.single.RollingNotCompleteTest which unfortunately can only intermittently reproduce the issue.

What it does, is to open a writingDocument and leave it open, which should prevent anything else writing to the queue until timeout. The test shows that sometimes we do succeed in writing. I believe that rolling is implicated but I could be completely wrong.

**Comment by RobAustin** [comment] 2017-10-30 21:36
you sometimes have to run this thousands of times before it fails, but it does fail.

**Comment by epickrram** [comment] 2017-10-31 13:40
This is not a locking problem. The test fails when it is executed over the boundary of a second:

main thread @ 13:37:01
 - create appender and write entry, leaving document open (20171031-133701.cq4)
writer thread @ 13:37:02
 - create appender and write entry (20171031-133702.cq4)

test fails because writer managed to write an entry.

This looks like expected behaviour to me, unless this is an edge case that needs to be handled. In this scenario, what actor has the responsibility of writing the EOF entry in the first queue file?

**Comment by JerryShea** [comment] 2017-10-31 20:27
So because the lock is in an "old" file then other appenders are able to progress without any problems? Is that what we want? Isn't the write lock designed prevent *all* appenders from progressing?

When I run the test I see
```[Thread-3] WARN net.openhft.chronicle.queue.impl.single.TimedStoreRecovery - Unable to write a header at header number: 59f8db1dffffffff position: 524744 switching to a corrupt meta data message```
when we try and get the writingDocument in the thread, so some kind of recovery is taking place, but it is not waiting for the timeout.
And, also, if we try and close the initialContent at the end of the test, it blows up with
```java.lang.IllegalStateException: Data was written after the end of the message, zero out data before rewinding [pos: 524750, rlim: 524750, wlim: 17301964, cap: 140737488355328 ] ٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠٠\u0080@¸.ǁ‡!! Skipped due to recovery of locked header !!\u008EËÿ٠٠٠٠٠٠
```

**Comment by RobAustin** [comment] 2017-10-31 20:36
The lock prevents two or more appenders writing to the same file at the same time, but I don’t see any reason to enforce the lock between files. What do you think. ?

**Comment by dpisklov** [comment] 2017-10-31 20:40
Not sure how we should behave here. One appender writes lock, other
appender rules to a new file but it should first write EOF to old file.
Does it overwrite lock file or does it just write EOF after lock? I think
it should wait until lock is free and then write EOF, so in essence we
should enforce lock between files in this sense.

**Comment by JerryShea** [comment] 2017-11-01 04:29
I agree that the lock makes sense at file scope i.e. other appenders could and should be able to continue to write even if one appender has a lock in an old file.
But, there are still some funnies happening here i.e. why are we seeing 
```
[Thread-3] WARN net.openhft.chronicle.queue.impl.single.TimedStoreRecovery - Unable to write a header at header number: 59f8db1dffffffff position: 524744 switching to a corrupt meta data message
```
?

**Comment by peter-lawrey** [comment] 2017-11-01 06:39
Certainly this header number is wrong.
ᐧ

**Comment by RobAustin** [comment] 2017-11-01 07:02
How many messages were written when this occurred in the test ?

**Comment by JerryShea** [comment] 2017-11-01 07:08
1 was written (but writingDocument not closed) then the Thread wrote another 1

**Comment by epickrram** [comment] 2017-11-01 09:41
headerNumber is being calculated as:

`wire.headerNumber(rollCycle.toIndex(cycle, 0) - 1);`

the RollCycle used in the test is TEST_SECONDLY, so the cycles comes out as something around `1509529212`, giving a header number of:

`6483378597896650751`
`0x59f9967bffffffff`

**Comment by epickrram** [comment] 2017-11-01 09:51
@JerryShea I reduced the timeout to 1 second, since it was enough to demonstrate the issue. The write thread does appear to wait for the timeout period, you can confirm by increasing the timeout to something more human-noticeable.

Do we need to handle the closure of the initial DocumentContext? We are in a scenario where a writer has taken longer than the timeout to complete writing a message, and another thread has already performed clean-up. The writing thread should throw an exception at this point, in order to indicate that its message was not successfully written to the queue. Admittedly, the error message could be clearer, but I don't think the current behaviour is incorrect.

**Comment by epickrram** [comment] 2017-11-01 10:48
@dpisklov EOF behaviour doesn't work in this scenario. In `QueueFiles.writeEOFIfNeeded`, we use the store's writePosition to check for EOF. When a queue has zero messages, writePosition is zero, so we end up reading the first four bytes of the queue:

`7d 01 00 40`

which is always non-zero, so no EOF marker is written. An initial writePosition of zero is invalid - it should be set to the length of the header so that it actually points to the position where the first record will be written. I'm going to have a look at fixing that now.

**Comment by dpisklov** [comment] 2017-11-01 11:32
@epickrram `QueueFiles.writeEOFIfNeeded` is only supposed to fix EOF for files created before the application was stopped. If the file was normally rolled during current run, it should have EOF written by `StoreAppender.rollCycleTo`:
```
private void rollCycleTo(int cycle) throws UnrecoverableTimeoutException {
            if (wire != null) {
                // only a valid check if the wire was set.
                if (this.cycle == cycle)
                    throw new AssertionError();
                try {
                    store.writeEOF(wire, timeoutMS());
                } catch (TimeoutException e) {
                    Jvm.warn().on(SingleChronicleQueueExcerpts.class, "Unable to terminate the previous cycle, continuing", e);
                }
            }
            setCycle2(cycle, true);
        }
```
Also, for any write position, we expect non-zero header, simply to use it as a length of message to skip:
```
long l = qs.writePosition();
Bytes<?> bytes = w.bytes();
long len = Wires.lengthOf(bytes.readVolatileInt(l));
long eofOffset = l + len + 4L;
```

**Comment by epickrram** [comment] 2017-11-01 11:43
Understood. There is a situation (process attempts to write first record in cycle, then dies without closing the context), where this will not work. In this case, the call to `qs.writePosition()` will return zero, which is the start of the queue file, not a valid record. It then tries to skip ~380 bytes and checks whether the int value at that point, which will never be zero, so does not write an EOF marker.

**Comment by dpisklov** [comment] 2017-11-01 11:57
I guess that's fine, we have logic in tailer to recover if we are out of
current cycle.

**Comment by epickrram** [comment] 2017-11-01 11:58
In the case of the test I have, the StoreTailer writes an EOF, so it gets fixed up anyway, but I think the `writeEOFIfNeeded` method should only try to perform the EOF if the writePosition is non-zero, and the length is not incomplete.

**Comment by dpisklov** [comment] 2017-11-01 12:02
Generally this method should ideally be called only on startup, and never
during normal rolling.

**Comment by epickrram** [comment] 2017-11-01 12:50
Winding back a bit, it looks as though everything is behaving as expected. The one oddity is that the header number is reported incorrectly in TimedStoreRecovery. 

So I think this issue reduces down to fixing the reporting of the headerNumber when recovering. Thoughts anyone?

**Comment by dpisklov** [comment] 2017-11-01 12:52
I think on some other thread @peter-lawrey agreed that we shouldn't report header number at all as it is always reset to Long.MIN_VALUE before going to recovery.

**Comment by epickrram** [comment] 2017-11-01 13:36
I've updated the warning message to contain the correct header number, otherwise all looks ok. closing.

**Closed by epickrram** 2017-11-01 13:36 UTC

**Comment by JerryShea** [comment] 2017-11-01 21:44
Thanks very much all...
I've done some more work on the test to document this behaviour (I hope) more clearly. I also renamed the test to AppenderLockOnlyAppliesToFileTest.

What it now does
- sets timeout to be greater than roll cycle time (1.5sec) and writes a message but doesn't close the context
- waits for more than roll cycle time but less than timeout and confirms we can write a message after roll but before timeout
- tries to read from the queue and confirms that
  - the header for the first message gets reset and so 1st message is lost
  - in performing the reset, we have waited for the timeout
