### ISSUE TITLE
non blocking tailer works as expected the first time around but blocks the thread when the remote source crashes

### ISSUE THREAD

**Issue by puiuvlad** [OpenHFT/Chronicle-Queue#181] opened 2015-07-29 00:34 UTC
Hi Luca,

I have a non blocking remote tailer connected to a source appender.

Initially the source is not there and the remote tailer performs as expected, i.e., tailer.nextIndex() returns 'false' immediately. Then I bring up the source, don't publish anything, and again, as expected, tailer.nextIndex() returns 'false' immediately. Then I bring down the source and this time tailer.nextIndex() returns 'false' but after 1 second. The expectatoin is that tailer.nextIndex() returns false immediately.

I am doing this in a loop (with two sink/source pairs) and I get this trace:

    07:06:50,306 WARN [net.openhft.chronicle.RemoteChronicleQueue.?] Failed to establish a connection [/127.0.0.1:15000]
    07:06:51,321 WARN [net.openhft.chronicle.RemoteChronicleQueue.?] Failed to establish a connection [/127.0.0.1:15001]
    07:06:52,336 WARN [net.openhft.chronicle.RemoteChronicleQueue.?] Failed to establish a connection [/127.0.0.1:15000]
    07:06:53,366 WARN [net.openhft.chronicle.RemoteChronicleQueue.?] Failed to establish a connection [/127.0.0.1:15001]
    07:06:54,381 WARN [net.openhft.chronicle.RemoteChronicleQueue.?] Failed to establish a connection [/127.0.0.1:15000]
    07:06:55,381 WARN [net.openhft.chronicle.RemoteChronicleQueue.?] Failed to establish a connection [/127.0.0.1:15001]
    07:06:56,410 WARN [net.openhft.chronicle.RemoteChronicleQueue.?] Failed to establish a connection [/127.0.0.1:15000]
    07:06:57,425 WARN [net.openhft.chronicle.RemoteChronicleQueue.?] Failed to establish a connection [/127.0.0.1:15001]

Can you please take a look?

Thanks,
Vladimir

**Comment by lburgazzoli** [comment] 2015-07-29 06:03
Which version?

**Comment by puiuvlad** [comment] 2015-07-29 10:00
3.4.3

**Comment by lburgazzoli** [comment] 2015-07-29 10:15
Can you test on 3.5.1, I remember a bug on the reconnection logic fixed in that version

**Comment by puiuvlad** [comment] 2015-07-29 10:29
Sure, I will.

**Comment by puiuvlad** [comment] 2015-07-30 02:15
Hi Luca,

I am getting the same behavior withe version 3.5.1:

    22:10:35,963 WARN [net.openhft.chronicle.RemoteChronicleQueue.?] Failed to establish a connection [/192.168.1.16:15001]
    22:10:36,964 WARN [net.openhft.chronicle.RemoteChronicleQueue.?] Failed to establish a connection [/192.168.1.16:15000]
    22:10:37,963 WARN [net.openhft.chronicle.RemoteChronicleQueue.?] Failed to establish a connection [/192.168.1.16:15001]
    22:10:38,963 WARN [net.openhft.chronicle.RemoteChronicleQueue.?] Failed to establish a connection [/192.168.1.16:15000]
    22:10:39,964 WARN [net.openhft.chronicle.RemoteChronicleQueue.?] Failed to establish a connection [/192.168.1.16:15001]
    22:10:40,965 WARN [net.openhft.chronicle.RemoteChronicleQueue.?] Failed to establish a connection [/192.168.1.16:15000]

Thanks,
Vladimir

**Comment by lburgazzoli** [comment] 2015-07-30 04:57
Ok, I will check

**Comment by lburgazzoli** [comment] 2015-08-01 09:51
Hi @puiuvlad 
I'm not able to reproduce the issue so I've created two simple examples:
- [ChronicleQueueReader](https://github.com/lburgazzoli/lb-chronicle/blob/master/chronicle-examples/chronicle-queue/src/main/groovy/com/github/lburgazzoli/openhft/examples/chronicle/queue/ChronicleQueueReader.groovy)
- [ChronicleQueueSink](https://github.com/lburgazzoli/lb-chronicle/blob/master/chronicle-examples/chronicle-queue/src/main/groovy/com/github/lburgazzoli/openhft/examples/chronicle/queue/ChronicleQueueSink.groovy)

They do not exchange any data and if I bring down the source after the first connection, I see the sink behaving as expected:
-  it returns false without any attempt to reconnect until the the reconnectionInterval has passed
-  after a configurable reconnection interval (reconnectionInterval) it attempts to reconnect and it warn if it failed to connect after a configurable number or attempts (reconnectionWarningThreshold)

So you'll won't see the warning immediately by after  reconnectionInterval * reconnectionWarningThreshold

**Comment by puiuvlad** [comment] 2015-08-01 18:08
Hi Luca, I will create a simple test program. It happens in certain
circumstances only. Vladimir

**Comment by lburgazzoli** [comment] 2015-08-01 18:26
Would be very useful

**Comment by puiuvlad** [comment] 2015-08-01 20:40
Hi Luca,

Class P creates a local source and a remote tailer. It then reads from the
tailer in a tight loop printing a trace line every time nextIndex takes
longer than 500 millis.

P1 and P2 are instances of P initialized such that each connects remotely
to the other's source.

Run P1 alone and you will see the trace lines every 1 second. Start P2 and
the trace lines will stop in P1's output. Stop P1 and the trace lines will
start appearing in P2's output.

I was wrong about the "first time" because I was creating the remote tailer
in P2 after P1 had already started.

I would expect that when the non blocking remote tailer is not connected to
the source nextIndex returns false right away no matter if the tailer had
never been connected or just disconnected a millisecond ago.

Thanks,
Vladimir

**Comment by lburgazzoli** [comment] 2015-08-03 06:15
Can you please provide an example showing the wrong behavior? it is not yet clear to me (my fault)

Then the nextIndex may not return false immediately as it may have some local data to read (it is lazy so it won't use the network until needed)

**Comment by puiuvlad** [comment] 2015-08-03 12:33
Hi Luca,

Hm, I had attached a jar file when I posted my message, but I cannot find it here today.

How should I pass the 3 files to you? I'll do that tonight when I get home.

Thanks,
Vladimir

**Comment by lburgazzoli** [comment] 2015-08-03 12:49
You can create a repo on your profile and add the file there if they do not contain any proprietary code or send me a mail at luca.burgazzoli at higherfrequencytrading dot com

**Comment by puiuvlad** [comment] 2015-08-03 23:14
Jar file sent via e-mail

**Comment by lburgazzoli** [comment] 2015-08-05 16:14
I've created a very similar example 

```groovy
@Grab(group='org.slf4j', module='slf4j-simple', version='1.7.12')
@Grab(group='net.openhft', module='chronicle', version='3.5.3')

import net.openhft.chronicle.*
import org.slf4j.*

System.setProperty('org.slf4j.simpleLogger.defaultLogLevel','debug')
System.setProperty('org.slf4j.simpleLogger.showDateTime','true')
System.setProperty('org.slf4j.simpleLogger.dateTimeFormat','HH:mm:ss:SSS')

def logger = LoggerFactory.getLogger("chronicle")
logger.info("path={}, sourcePort={}, remotePort={}", args[0],args[1], args[2])

def source = ChronicleQueueBuilder.indexed(args[0])
    .source()
    .bindAddress("localhost", args[1].toInteger())
    .build()

def client = ChronicleQueueBuilder.remoteTailer()
    .connectAddress("localhost", args[2].toInteger())
    .readSpinCount(1)
    .reconnectionWarningThreshold(1)
    .build()

def tailer = client.createTailer().toEnd()
while (true) {
    long startMillis = System.currentTimeMillis()

    if(tailer.nextIndex()) {
        tailer.finish()
    }

    long elapsedMillis = System.currentTimeMillis() - startMillis
    if (elapsedMillis > 500) {
        logger.info("it took {} > {} millis to return from nextIndex\n", elapsedMillis, 500)
    }
}
```

In my tests I've observed that sometimes the line "it took ..." appears but it is because of the time needed to establish a connection but ```nextIndex()``` never wait. 

The line "Failed to establish a connection" is logged when the client tries to open a new connection which happens only if the reconnection delay has expired, so ```nextIndex()``` does something like something like:

```java
    if(!connection.isOpen()) {
        if(reconnectionDelayHasExpired()) {
            return connection.open() && readData();
        } else {
            return false;
        }
    } else {
        return readData();
    }
```

I'm still missing something ?

**Comment by lburgazzoli** [comment] 2015-08-06 16:41
Can you also test the latest snapshot? I've removed some condition that might have had some impact on nextIndex

**Comment by puiuvlad** [comment] 2015-08-07 02:48
Hi Luca,

Yes, I will.

My use case is as follows. I have a list of tailers, some local and some remote, from which I am trying to read a record at a time, in round robin fashion, in a tight loop. It is imperative that tailer.nextIndex() returns immediately for both the local and remote tailers, in every invocation, otherwise my performance will suffer. 

Per your reply above, you are seeing the "it took..." message when there is no process at the other end of the remote tailer, meaning that in some circumstances (it does not really matter the actual cause) tailer.nextIndex() does not return right away. tailer.nextIndex() waits, there is no other explanation for seeing the "it took..." line in the output of this fragment:

    long startMillis = System.currentTimeMillis()

    if(tailer.nextIndex()) {
        tailer.finish()
    }

    long elapsedMillis = System.currentTimeMillis() - startMillis
    if (elapsedMillis > 500) {
        logger.info("it took {} > {} millis to return from nextIndex\n", elapsedMillis, 500)
    }

The circumstances when there is no source at the other end of the remote tailer are not under my control, since the remote process can crash/shut down at any time. I could (and I am) remove the remote tailers from the list of tailers as soon as I detect that the remote processes are gone, but this being a tight loop, I am always too late and performace suffers.

I used the "Failed to establish a connection" line as an indication that there was some delay in the processing. I would not care about it if it were occurring on a different thread. The real issue is the "it took..." line.

Thanks,
Vladimir

**Comment by lburgazzoli** [comment] 2015-08-07 05:33
I will have a look again but nextIndex definitively do not return immediately when the reconnection delay expires because the connection to the source is initiated by a call to mextIndex so what will happen is:
- if SocketChannel.open() fails it return false
- if SocketChanbel.open() succeed it sends the last know index to the source and it spins for a little while to check if there is data to read

To detect connection and disconnection you can use a connection listener (I need to check if it covers all the cases)

**Comment by peter-lawrey** [comment] 2015-08-07 06:34
Something to consider is that you can have local and remote sources.  This
means you can have say 3 appenders on one machine and another 5 remote
appenders on other machines all writing to the same Vanilla Chronicle..

**Comment by puiuvlad** [comment] 2015-08-18 02:04
Hi Luca,

I have tried the latest snapshot (chronicle 3.5.4-SNAPSHOT with lang 6.6.17-SNAPSHOT) but I am still getting the "it took..." line when executing the test program I sent you. Any update on your side?

Peter, is your comment addressed to me or to Luca?

Thanks,
Vladimir

**Comment by peter-lawrey** [comment] 2015-08-18 05:54
Hi Puiuvlad,
   It is more directed to yourself.  I was wondering if taking a different
approach might help.

Regards,
   Peter.

**Comment by peter-lawrey** [comment] 2016-06-27 15:00
Closing as Queue v3 is not supported.

**Closed by peter-lawrey** 2016-06-27 15:00 UTC
