### ISSUE TITLE
Strange Exit on Creating Tailer in multi-threaded situation

### ISSUE THREAD

**Issue by charliecciter** [OpenHFT/Chronicle-Queue#350] opened 2017-06-03 02:06 UTC
I tried a little test to see how I can have multiple threads access the content of ChronicleQueue I created with the following code.  However,  threads in my ExecutorService seems to exit erratically and inconsistently with the `ExcerptTailer tailer = tempQueue.createTailer();`.   If I run the same snippet multiple times, it sometimes gets all the ExcerptTailers, sometimes a few, sometimes none at all.   Each thread is creating its own ExerptTailer.   I am keeping track of indices added at append() stage.
This ExecutorService just exists without any Exception and ExecutorService never gets terminated.  I tried with InvokeAll() and Callables(), I had the same result.

ExecutorService newPool = Executors.newFixedThreadPool(2);

		for(int i= 0; i < 5; i++ ){
			int finalI = i;
			newPool.execute(new Runnable() {
				@Override
				public void run() {

					try (ChronicleQueue tempQueue = SingleChronicleQueueBuilder
							.binary(path)
							.rollCycle(RollCycles.HOURLY)
							.build()) {

						Long index = ChronicleQueueManager.getTailIndex();
					 	System.out.println("Got index Successfully");
						ExcerptTailer tailer = tempQueue.createTailer();
  
						System.out.println("Got the tailer successfully");

						if(tailer.moveToIndex(index)) {
							System.out.println(tailer.readingDocument().wire().read().text());
						}else {
							System.out.println("there is an error moving index");
						}

					} catch (Throwable e) {
						System.out.println("error " + e);

					}
				}
			});
		}

**Comment by peter-lawrey** [comment] 2017-06-03 05:59
I would create one queue with multiple tailers though it shouldn't matter
here.
Are all the tailers using the same index?

**Comment by charliecciter** [comment] 2017-06-05 16:20
nope, I keep track of a queue of indices when I add() an item to a SingleChronicleQueue.
Yes, I tried an implementation with one queue with multiple tailers and I had the same result..

index: 1785340595535872
index: 1785340595535873
index: 1785340595535874
index: 1785340595535875
index: 1785340595535876

**Comment by sergebg** [comment] 2017-06-07 22:48
Probably, the exception stack trace could help.

**Comment by epickrram** [comment] 2017-08-17 08:06
@charliecciter can you post the entire test case in a gist? That will make it easier to investigate.

**Comment by epickrram** [comment] 2017-09-20 12:42
Possible duplicate of #378 , please re-test with latest from master.

**Comment by RobAustin** [comment] 2017-12-29 14:24
@charliecciter I'm going to close this as we feel this is a duplicate of  #378, please reopen if this is not the case.

**Closed by RobAustin** 2017-12-29 14:24 UTC
