### ISSUE TITLE
non blocking remote tailer creates garbage in Windows

### ISSUE THREAD

**Issue by puiuvlad** [OpenHFT/Chronicle-Queue#171] opened 2015-06-20 11:05 UTC
Hi,

I am using non blocking remote tailers in a tight loop:

_chronicle = ChronicleQueueBuilder.remoteTailer().connectAddress(host, port).readSpinCount(1).build();
_tailer = _chronicle.createTailer();

This seems to create a lot of garbage that is reclaimed by the GC leading to about 12 pauses of 1-2-5 ms per 30 seconds.

The culprit seems to be the VanillaSelector.select, which invokes selector.selectNow.

```
    public int select(int spinLoopCount, long timeout) throws IOException {
        for (int i = 0; i < spinLoopCount; i++) {
            int nbKeys = selector.selectNow();
            if (nbKeys != 0) {
                return nbKeys;
            }
        }

        return selector.select(timeout);
    }
```
![selectnow-creates-garbage](https://cloud.githubusercontent.com/assets/9600467/8266998/ba8e3c30-171a-11e5-9a1f-23a07b737413.PNG)
![selectnow-creates-garbage-gc-times](https://cloud.githubusercontent.com/assets/9600467/8266999/ba90d4d6-171a-11e5-9b96-c238301a20c6.PNG)

According to the attached FlightRecorder results, selectNow down the invocation stack creates ArrayList iterator objects, and also FdMap.get apparently creates additional garbage.

Can you think of a different non blocking remote tailer implementation that would not create as much garbage?

Thanks,
Vladimir

**Comment by lburgazzoli** [comment] 2015-06-20 12:12
Could you please tell us which version are you using?

**Comment by puiuvlad** [comment] 2015-06-20 15:34
chronicle 3.4.3

**Comment by peter-lawrey** [comment] 2015-06-20 18:06
Hello Puiuvlad,
   Thank you for pointing that out.  On Linux there is patch to the built
in socket handling to not create this garbage.  The short term work around
is to not use busy waiting on Windows.
   Luca, can you disable it on Windows until we have a fix.

Regards,
   Peter.

**Comment by puiuvlad** [comment] 2015-06-21 11:50
Hi Peter,

Which version of Java has the patch on Linux?  I am using 1.7.0_76 on Windows, as I don't have a Linux machine. Since Java 7 has reached its end of life, is it reasonable for me to expect a patch for this issue on Windows from Oracle? I could upgrade to Java 8 if required.

Would you contact Oracle or should I? In your experience, how responsive are they in fixing this kind of issues?

Thanks,
Vladimir

P.S. Needless to say that remote non blocking tailers are a very useful feature in Chronicle Queue...

**Comment by lburgazzoli** [comment] 2015-06-21 13:49
Peter is talking about a workaround we have added to our code to reduce the garbage generate by NIO selector.

I need to check why it does not work as expected on Windows.

**Comment by peter-lawrey** [comment] 2015-06-21 15:43
Hello Puiuvlad,

As far as I know, Oracle don't consider the issue to be a bug in the JVM
nor do they plan to fix it.  It has been there for more than ten years.
The workaround is a patch we added.

I believe Oracle is responsive if you pay for support, but I have never
received a reply for a free bug report in 16 years of working on Java.

In terms of licensing,

http://www.oracle.com/us/corporate/pricing/technology-price-list-070617.pdf

Over five years, Oracle charge $10,500 per processor for a license and
support.  Not surprisingly, not many places I know of pay this.

Regards,
   Peter.

**Comment by lburgazzoli** [comment] 2015-06-28 19:49
Hi @puiuvlad,

could you please post how you create the source? Your FlightRecorder screen-shot shows that excessive allocation comes from SourceTcp which is not supposed to invoke selectNow() unless the timeout is set to 0

**Comment by puiuvlad** [comment] 2015-06-29 02:38
Hi Luca,

The source is created in the remote process, like so:
```
	if (concurrentWrites) {
		_chronicle = ChronicleQueueBuilder.vanilla(fileName).build();
	} else {
		_chronicle = ChronicleQueueBuilder.indexed(fileName).build();
	}
	_appender = _chronicle.createAppender();
	_source = ChronicleQueueBuilder.source(_chronicle).bindAddress(Utils._localhost, port).build();
```

I don't think I am explicitly setting a timeout parameter to 0.

Thanks,
Vladimir

**Comment by lburgazzoli** [comment] 2015-07-07 15:26
We have done some research on the cause of the garbage and the root is in the implementation of sun.nio.ch.WindowsSelectorImpl and it is caused by:
- use of iterations (in foreach loop)
- explicit instantiation of Integers instead of autoboxing (which may cache some values)

I wrote an implementation of the WindowsSelectorImpl which partially addresses the issues above and the results are:

![windowsselectorpatched](https://cloud.githubusercontent.com/assets/1868933/8549644/370454e8-24cc-11e5-8878-47ed2fdb5741.png)

Here the very same code without the "patch":

![windowsselector](https://cloud.githubusercontent.com/assets/1868933/8549653/3d161bbe-24cc-11e5-9f5e-57854ef84829.png)


I will issue a Java bug as soon as possible.

**Comment by puiuvlad** [comment] 2015-07-17 01:28
Hi Luca,

Did you have a chance to create a workaround? Which artifact/version has the fix?

Thanks,
Vladimir

**Comment by lburgazzoli** [comment] 2015-07-20 07:16
Hi Vladimir,
for 'academic' purpose you can get the WindowsSelectorImpl source code, patch it and replace it via  -Xbootclasspath/p but you can't deploy it as it violates the Java license:

```
-Xbootclasspath/p:path

    Specifies a list of directories, JAR files, and ZIP archives separated by semicolons (;) to prepend to the front of the default bootstrap class path.
    Do not deploy applications that use this option to override a class in rt.jar, because this violates the JRE binary code license.
```

**Comment by puiuvlad** [comment] 2015-07-21 01:30
Hi Luca,

Two questions: (1) where would I find the source for WindowsSelectorImpl for the specific version of Java that I am using? I cannot find package sun.nio.ch in the src.zip in my JDK installation. (2) did you by any chance file a bug report with Oracle for this issue?

Thanks,
Vladimir

**Comment by lburgazzoli** [comment] 2015-07-21 08:45
1) in OpenJDK, src.zip does not include sun.* packages
2) not yet, I'd like to provide a benchmark showing it but I had not time yet

**Comment by peter-lawrey** [comment] 2016-06-27 14:58
Closing as Queue v3 is not supported.

**Closed by peter-lawrey** 2016-06-27 14:58 UTC
