### ISSUE TITLE
Too many open files 

### ISSUE THREAD

**Issue by MartyIX** [OpenHFT/Chronicle-Queue#357] opened 2017-06-28 06:43 UTC
Hi,

my environment is:

* Chronicle Queue: 4.6.6
* OS: Ubuntu 17.04
* `ulimit -n` reports: 1024

I have started my program at: 2017-06-27 15:00 UTC and it was running till now (one rolling should occurred). I have my log full of errors like these (please note that the file `20170628.cq4` exists):

```
2017-06-28 05:09:37,075 [miniTrader.brain.events-0] ERROR [L35] com.wikidi.golem.shared.utils.EventListener.notifyListenersException:
java.io.FileNotFoundException: data/marketDataQueue/20170628.cq4 (Too many open files)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at net.openhft.chronicle.bytes.MappedFile.of(MappedFile.java:114)
	at net.openhft.chronicle.bytes.MappedBytes.mappedBytes(MappedBytes.java:92)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.mappedBytes(SingleChronicleQueue.java:560)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue$StoreSupplier.acquire(SingleChronicleQueue.java:607)
	at net.openhft.chronicle.queue.impl.WireStorePool.acquire(WireStorePool.java:80)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.storeForCycle(SingleChronicleQueue.java:305)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.setCycle2(SingleChronicleQueueExcerpts.java:224)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.rollCycleTo(SingleChronicleQueueExcerpts.java:598)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:289)
	at net.openhft.chronicle.wire.MarshallableOut.writingDocument(MarshallableOut.java:55)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writeText(SingleChronicleQueueExcerpts.java:134)
	at com.myproject.MarketDataChronicleQueue.passMessage(MarketDataChronicleQueue.java:25)
```

where `MarketDataChronicleQueue.java` looks like this:

```
package com.myproject;

import net.openhft.chronicle.queue.impl.single.SingleChronicleQueue;
import net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.ParametersAreNonnullByDefault;

@ParametersAreNonnullByDefault
public class MarketDataChronicleQueue {

    private static final Logger logger = LoggerFactory.getLogger(MarketDataChronicleQueue.class);
    private static final SingleChronicleQueue queue;

    static {
        String path = "data/marketDataQueue"; // @todo make it absolute path
        queue = SingleChronicleQueueBuilder.binary(path).build();
    }


    public static void passMessage(String message) {
        logger.trace("(message:{})", message);

        queue.acquireAppender().writeText(message);

        logger.trace("(-)");
    }
}
```

Is there something I do obviously wrong? I call `MarketDataChronicleQueue.passMessage` from multiple threads.

Regards,
Martin

**Comment by MartyIX** [comment] 2017-06-28 07:54
I have tried to initialize the queue like this:

        queue = SingleChronicleQueueBuilder
                .binary(path)
                .rollCycle(RollCycles.TEST_SECONDLY)
                .build();

and then when I watch output of `ls -l /proc/<pid>/fd` I can see that the number of file descriptors grow (I was watching a minute or so):

```
lrwx------ 1 marty marty 64 čen 28 09:50 32 -> /home/marty/work/project/data/marketDataQueue/20170628-075014.cq4
lrwx------ 1 marty marty 64 čen 28 09:50 33 -> /home/marty/work/project/data/marketDataQueue/20170628-075115.cq4
lrwx------ 1 marty marty 64 čen 28 09:50 34 -> /home/marty/work/project/data/marketDataQueue/20170628-075033.cq4
lrwx------ 1 marty marty 64 čen 28 09:50 35 -> /home/marty/work/project/data/marketDataQueue/20170628-075052.cq4
lrwx------ 1 marty marty 64 čen 28 09:50 36 -> /home/marty/work/project/data/marketDataQueue/20170628-075111.cq4
```

Hopefully that helps

**Comment by MartyIX** [comment] 2017-06-28 08:27
It seems `rollCycle` is not the culprit. I was running my code for 20 minutes and I can see like 5 file descriptors in the output of `ls -l /proc/<pid>/fd`.

**Comment by peter-lawrey** [comment] 2017-06-28 08:32
To use up 1000 file descriptors you would have to run for ~17 mins at one
per second.

This is something we should fix. Are we getting more than one file per
second?

Regards Peter.

**Comment by peter-lawrey** [comment] 2017-06-28 08:33
Can you get a list of the open files with lsfo or ls -l /proc/{pid}/fd

On 28 Jun. 2017 09:32, "Peter Lawrey" <peter.lawrey@chronicle.software>
wrote:

To use up 1000 file descriptors you would have to run for ~17 mins at one
per second.

This is something we should fix. Are we getting more than one file per
second?

Regards Peter.

**Comment by MartyIX** [comment] 2017-06-28 08:39
This is output for my latest program run with `ls -l /proc/{pid}/fd`:
```
lrwx------ 1 marty marty 64 Jun 28 08:33 41 -> /home/marty/work/data/marketDataQueue/20170628.cq4
lrwx------ 1 marty marty 64 Jun 28 08:33 42 -> /home/marty/work/data/marketDataQueue/20170628.cq4
lrwx------ 1 marty marty 64 Jun 28 08:33 43 -> /home/marty/work/data/marketDataQueue/20170628.cq4
lrwx------ 1 marty marty 64 Jun 28 08:33 45 -> /home/marty/work/data/marketDataQueue/20170628.cq4
lrwx------ 1 marty marty 64 Jun 28 08:33 46 -> /home/marty/work/data/marketDataQueue/20170628.cq4
lrwx------ 1 marty marty 64 Jun 28 08:33 48 -> /home/marty/work/data/marketDataQueue/20170628.cq4
lrwx------ 1 marty marty 64 Jun 28 08:34 49 -> /home/marty/work/data/marketDataQueue/20170628.cq4
lrwx------ 1 marty marty 64 Jun 28 08:34 51 -> /home/marty/work/data/marketDataQueue/20170628.cq4
lrwx------ 1 marty marty 64 Jun 28 08:35 52 -> /home/marty/work/data/marketDataQueue/20170628.cq4
lrwx------ 1 marty marty 64 Jun 28 08:35 54 -> /home/marty/work/data/marketDataQueue/20170628.cq4
lrwx------ 1 marty marty 64 Jun 28 08:35 55 -> /home/marty/work/data/marketDataQueue/20170628.cq4
lrwx------ 1 marty marty 64 Jun 28 08:35 57 -> /home/marty/work/data/marketDataQueue/20170628.cq4
```

**Comment by MartyIX** [comment] 2017-06-28 08:41
It is not like 1 FD per 1 second. It's slower process. I'm trying to send names of threads I use to put data to queue to get more information about the issue.

**Comment by MartyIX** [comment] 2017-06-28 08:47
When I modify my code from


    public static void passMessage(String message) {
        logger.trace("(message:{})", message);

        queue.acquireAppender().writeText(message);

        logger.trace("(-)");
    }

to

    public static void passMessage(String message) {
        logger.trace("(message:{})", message);

        excerptAppender.writeText(message);

        logger.trace("(-)");
    }

I can see only one opened FD. And it does not grow. I have found out that the queue is used only by one thread so I can modify my code like this.

**Comment by scottkidder** [comment] 2017-06-28 15:24
I've had to use the same workaround. The acquired appender appears to be collected (WeakRef) and even stranger it doesn't release the FD.

**Comment by epickrram** [comment] 2017-06-29 07:44
What version of the JVM does this problem manifest on?

**Comment by MartyIX** [comment] 2017-06-29 07:46
```
$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.17.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by epickrram** [comment] 2017-06-29 08:21
Thank you. I'm trying to reproduce the issue from your code example above.
I've added a test, can you update and try to run this in your environment to see if it exhibits the issue?

https://github.com/OpenHFT/Chronicle-Queue/blob/master/src/test/java/net/openhft/chronicle/queue/impl/single/AppenderFileHandleLeakTest.java

**Comment by MartyIX** [comment] 2017-06-29 08:48
```
mvn test -Dtest=net.openhft.chronicle.queue.impl.single.AppenderFileHandleLeakTest >AppenderFileHandleLeakTest.log
```

Result: 

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building OpenHFT/Chronicle-Queue 4.6.7-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ chronicle-queue ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/marty/work/golem/temp/Chronicle-Queue/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ chronicle-queue ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-bundle-plugin:2.5.3:manifest (default) @ chronicle-queue ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ chronicle-queue ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ chronicle-queue ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.16:test (default-test) @ chronicle-queue ---
[INFO] Surefire report directory: /home/marty/work/golem/temp/Chronicle-Queue/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running net.openhft.chronicle.queue.impl.single.AppenderFileHandleLeakTest
start count: 44
end count: 44
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.6 sec - in net.openhft.chronicle.queue.impl.single.AppenderFileHandleLeakTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.464 s
[INFO] Finished at: 2017-06-29T10:46:04+02:00
[INFO] Final Memory: 15M/248M
[INFO] ------------------------------------------------------------------------
```

More verbose (with `-X` option): https://pastebin.com/3ZXc7kf6

**Comment by epickrram** [comment] 2017-06-29 08:54
That test case looks pretty similar to the code you initially described - can you try to modify the test case, or supply your own, so that I can reproduce the issue?

**Comment by MartyIX** [comment] 2017-06-29 09:01
I'll try

**Comment by MartyIX** [comment] 2017-06-29 09:55
I have been trying for half an hour and it always reports a correct number. I'm not sure what is different from my project though.

**Comment by epickrram** [comment] 2017-06-29 10:02
Without a means to reproduce the issue, it's hard to diagnose and confirm a fix.
Can you create a single-class reproduction program that you can share?

**Comment by MartyIX** [comment] 2017-06-29 10:10
I'm aware of that. I don't have currently time to write a test case. Your test case seems very similar to my use case so I'm not sure what the issue is. 

I can have a look at it in a few days and report if I find something amiss. I'll close the issue until then.

**Comment by sergebg** [comment] 2017-06-29 15:57
The problem was reported earlier. I can provide a test.

**Comment by MartyIX** [comment] 2017-06-29 18:06
@sergebg Should I re-open the issue then?

**Comment by sergebg** [comment] 2017-06-29 18:10
I think that this is a critical issue, and it can be reproduced, and so it makes sense to re-open it.

**Comment by scottkidder** [comment] 2017-06-29 18:40
Test for this in #358

**Comment by epickrram** [comment] 2017-06-30 07:10
Thanks @sergebg  for the test case, I will try to reproduce and take a look at this today.

**Comment by epickrram** [comment] 2017-06-30 13:35
Hi folks, I believe this is now fixed. Please update to latest and re-test.

**Comment by epickrram** [comment] 2017-07-03 14:52
Update: it occurred to me that a cleaner solution is to make the `ExcerptAppender` and `ExcerptTailer` extend `Closeable`. The approved procedure for using these objects will be to wrap them in a try-with-resources block.

@MartyIX your example from above should be re-written as:

```
public static void passMessage(String message) {
    logger.trace("(message:{})", message);

    try(ExcertAppender appender = queue.acquireAppender()) {
           appender.writeText(message);
    }

    logger.trace("(-)");
}
```

**Comment by MartyIX** [comment] 2017-07-03 14:53
@epickrram Thank you :-)

**Comment by epickrram** [comment] 2017-07-03 15:25
Actually, scratch that - using Closeable means that the appenders can't be re-used as thread-locals. I'm reverting that change, so for now, just keep creating appenders, and the weak-reference processing will clean them up.

**Comment by epickrram** [comment] 2017-07-07 10:40
We're going to stick with the ReferenceQueue solution for now, since making the cached Appenders/Tailers AutoClosable doesn't really make sense.

**Closed by epickrram** 2017-07-07 10:40 UTC

**Comment by anirudh-striim** [comment] 2018-11-21 21:56
I am seeing this issue with 5.16.11 version now. Do I need to update my version ?

**Comment by dpisklov** [comment] 2018-11-22 00:31
Try latest (bom 2.17.48 should do). We do not recommend just using Queue version.

**Comment by anirudh-striim** [comment] 2018-11-22 00:49
So I use two maven dependencies, chronicle-bom and chronicle-queue ? What is bom doing in this specific context if I may know.

**Comment by dpisklov** [comment] 2018-11-22 13:32
```
    <dependencyManagement>
        <dependencies>
        ...
            <dependency>
                <groupId>net.openhft</groupId>
                <artifactId>chronicle-bom</artifactId>
                <version>2.17.48</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        ...
        </dependencies>
    </dependencyManagement>
    <dependencies>
        ...
        <dependency>
            <groupId>net.openhft</groupId>
            <artifactId>chronicle-queue</artifactId>
        </dependency>
        ...
    <dependencies>
```
For more info please read Maven docs
