### ISSUE TITLE
Review and fix Bytes read limits

### ISSUE THREAD

**Issue by rogersimmons** [OpenHFT/Chronicle-Queue#1094] opened 2022-05-24 07:16 UTC
While tracing through [ChronicleQueueTwoThreadsTest](https://github.com/OpenHFT/Chronicle-Queue/blob/ea/src/test/java/net/openhft/chronicle/queue/ChronicleQueueTwoThreadsTest.java) and monitoring the readLimit on the reader's [BinaryReadDocumentContext](https://github.com/OpenHFT/Chronicle-Wire/blob/ea/src/main/java/net/openhft/chronicle/wire/BinaryReadDocumentContext.java), the readLimit seems excessively large: 140737488355328

In particular, this part of BinaryReadDocumentContext.close():
````
        if (readLimit0 > 0 && wire0 != null) {
            @NotNull final Bytes<?> bytes = wire0.bytes();
            bytes.readLimit(readLimit0);
            if (wire.usePadding())
                readPosition0 += BytesUtil.padOffset(readPosition0);
            bytes.readPosition(Math.min(readLimit0, readPosition0));
        }
````

Here, the readLimit is 140737488355328 which far exceeds the actual data available in the queue for reading (written concurrently by the other thread in the test)

**Comment by alamar** [comment] 2022-11-17 16:06
I believe it is
> net.openhft.chronicle.bytes.MappedFile#DEFAULT_CAPACITY = 128L << 40;

**Comment by alamar** [comment] 2022-11-17 16:12
It gets into `writePosition` in `net.openhft.chronicle.bytes.AbstractBytes#uncheckedWritePosition`

**Comment by alamar** [comment] 2022-11-17 16:14
And `AbstractBytes.readLimit` is `writePosition` so it seeps from `ChunkedMappedBytes`.

**Comment by alamar** [comment] 2022-11-17 16:15
So I'm just not sure which one of those is not by design @rogersimmons

**Comment by alamar** [comment] 2022-11-25 10:21
I will close this ticket, please reopen if there's any specific failure mode here.

**Closed as completed by alamar** 2022-11-25 10:21 UTC
