### ISSUE TITLE
java.lang.InternalError in java.io.UnixFileSystem.list

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#774] opened 2020-12-07 17:11 UTC
This is thought to be related to rolling.

This warning pops up after running for a while:

2020-12-05_08:07:57.769 [main/s-0core-event-loop] WARN  n.o.c.t.VanillaEventLoop - 
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
        at java.io.UnixFileSystem.list(Native Method) ~[?:1.8.0_261]
        at java.io.File.list(File.java:1122) ~[?:1.8.0_261]
        at java.io.File.listFiles(File.java:1248) ~[?:1.8.0_261]
        at net.openhft.chronicle.queue.impl.single.TableDirectoryListing.refresh(TableDirectoryListing.java:71) ~[chronicle-queue-5.20.113.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.setFirstAndLastCycle(SingleChronicleQueue.java:687) ~[chronicle-queue-5.20.113.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.lastCycle(SingleChronicleQueue.java:714) ~[chronicle-queue-5.20.113.jar:?]
        at net.openhft.chronicle.queue.impl.single.StoreTailer.nextIndexWithNextAvailableCycle(StoreTailer.java:493) ~[chronicle-queue-5.20.113.jar:?]
        at net.openhft.chronicle.queue.impl.single.StoreTailer.endOfCycle(StoreTailer.java:320) ~[chronicle-queue-5.20.113.jar:?]

**Comment by RobAustin** [comment] 2020-12-07 17:41
the code should be rerun with:
```
-Djvm.safepoint.enabled=true -Djvm.resource.tracing=true
```
Note: these will slow it down

**Comment by glukos** [comment] 2020-12-16 15:23
The original root cause is probably fixed in OpenHFT/Chronicle-Queue#781

**Comment by glukos** [comment] 2021-01-08 13:51
The error wasn't reproduced after https://github.com/OpenHFT/Chronicle-Queue/issues/781 fix. Closing the issue

**Closed by glukos** 2021-01-08 13:51 UTC
