### ISSUE TITLE
Issues with the pretoucher when used for reading instead of writing.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#326] opened 2017-01-13 11:59 UTC
The problem in the second one occurs as the underlying MappedBytes is changing so ti has to reset the position for the new MappedBytes object.  It appears the file is the same so it's not clear why it would create a new one. Continuing to investigate.

**Comment by scottkidder** [comment] 2017-07-18 18:03
I'm seeing something strange possibly related to this. It seems that now if my Chronicle-Queue reader (with a pretoucher) experiences a GC (I am periodically forcing one) then the pretoucher causes Allocation of all chunks from the beginning of the queue being read.

[pretouch_walking_after_gc.txt](https://github.com/OpenHFT/Chronicle-Queue/files/1156860/pretouch_walking_after_gc.txt)

I will try to setup a repro test, but am putting this here in the case that this may be an obvious fix considering the recent ThreadLocal resource cleaning changes.

**Comment by epickrram** [comment] 2017-07-19 09:57
The PretouchHandler's ExcerptAppender can be cleaned up by the GC, and I've observed this. However, when it is recreated by the acquireAppender() call, the new instance of the Pretoucher still has a reference to the same underlying store.

In order for the Pretoucher to start touching all chunks from zero, the writePosition of the underlying WireStore would need to be zero. I can't see any reason why a GC would cause this; still investigating.

**Comment by scottkidder** [comment] 2017-07-19 13:55
Thanks for looking into this Mark. I should've mentioned that the writing appender is using lazyIndexing. Could this be causing the bad interaction, seeing that the PretoucherState is using `() -> this.store.writePosition()` to get

**Comment by epickrram** [comment] 2017-07-19 15:12
That's good to know, I'll take a closer look at that behaviour.

**Comment by scottkidder** [comment] 2017-07-19 20:31
I've determined that this is in fact being caused by the writing appender using lazy indexing. How can we change the PretoucherState `posSupplier` to work in this case?

**Comment by epickrram** [comment] 2017-07-20 09:11
Scott,
can you share a little more information about your setup, and how you confirmed the cause? I'd like to start with a test case that demonstrates the issue before starting to work on a solution.

**Comment by epickrram** [comment] 2017-07-20 15:41
Scott,
I've managed to recreate the issue with a simpler test case. I'll look into the cause/possible solutions.

**Comment by epickrram** [comment] 2017-07-21 10:11
Scott,
I've added a `Pretoucher` class that is separate to the appender (they seem like separate concerns when used from another thread). This works around the lazy-indexing problem, but could be a source of resource leaks if not correctly cleaned up. Since the `PretouchHandler` is (presumably) long-lived, I doubt this will be an issue.

If there is a requirement for the resources held by the `Pretoucher` to be automatically cleaned up, I can look at adding more weak-reference processing, though I believe in this case that it should be the responsibility of the user to close things properly.

Can you try out the new `PretouchHandler` and see if it addresses your issue?

**Comment by epickrram** [comment] 2017-10-11 08:27
Closing due to no further activity.

**Closed by epickrram** 2017-10-11 08:27 UTC

**Comment by hft-team-city** [comment] 2022-02-02 13:15
Released in [Chronicle-Queue-5.22ea16](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.22ea16), [BOM-2.22ea106](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea106)
