### ISSUE TITLE
Check Java: Lock not released on exception accessing new file

### ISSUE THREAD

**Issue by rogersimmons** [OpenHFT/Chronicle-Queue#697] opened 2020-07-30 09:41 UTC
Issue observed in C++ Queue. Check Java

2 appenders writing to a queue. Due to external misconfiguration, when Appender-1 rolls, the new file is created with permissions which block access to Appender-2. When Appender-2 attempts to access the file (StoreAppender.writingDocument(bool)) an exception is thrown after acquiring the lock, but the lock is not released. This blocks further access to the queue from Appender-2 even after the underlying permission issue has been resolved.

**Comment by glukos** [comment] 2021-06-28 10:53
@rogersimmons 
As I understand, the issue can be simplified to the following test case:
1. Set up file permissions so process X doesn't have access to queue segment S
2. Create an appender within X so it should roll to S and start writing into it
3. Write attempt fails with exception, which is expected
4. Set up file permissions so process X now can write to S
5. Next attempt to write to S from process X should be successful

Also, please tell me if the issue is not relevant and we can close it.

**Comment by rogersimmons** [comment] 2021-06-28 11:40
@glukos
Suggest first take a look at https://github.com/ChronicleEnterprise/Chronicle-Dev-CPP/commit/7dabaad5e213ce175bf00b59d237b68466bcf21b - in particular the Issue1.cpp testcase which was added to cover 
(there's a large comment block at the head of the test case describing the scenario)

The test can be ported to Java more or less directly. It may run green straight out of the box by now.
Let me know if the test fails on Java and I can help with porting the fix to Java (2 extra try/catch blocks in ScopedBytesWriter and StoreAppender).

Thanks

**Comment by glukos** [comment] 2021-06-28 19:16
@rogersimmons Thank you.
I've ported issue1 test to Java, it runs green.

**Closed** 2021-06-29 05:36 UTC
